### ISSUE TITLE
Add GitHub actions to run unit tests for the kata

### ISSUE THREAD

**Issue by johnjstuart** [BNYMellon/graphql-kata#1]
All code should be compiled and the unit tests in the solutions module should be executed as part of a GitHub actions build.

**Comment by codewalk** [comment]
I have created below PR to have Github build action call. It will perform mvn package goal, which will compile and run test cases.
https://github.com/BNYMellon/graphql-kata/pull/5
Please have a look and let me know if anything else is required

![Screenshot 2023-04-03 230357](https://user-images.githubusercontent.com/2845897/229584791-23ea68fc-7935-47a5-bdc2-4d053f9530b6.png)
